openapi: 3.0.0
info:
  title: malfunctions
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /malfunctions:
    get:
      summary: get malfunctions on route
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/vehicle.v1.yaml
        '':
          description: ''
      parameters:
        - name: vehicle
          in: query
          description: ''
          schema:
            type: array
            items:
              $ref: ../models/vehicle.v1.yaml
    parameters: []
components:
  schemas: {}
