openapi: 3.0.0
info:
  title: Bahn API
  description: Bahn API
  version: '1.0'

servers:
  - url: http://localhost/v1

paths:
  /routes:
    $ref: "passenger-info.v1.yaml#/paths/~1routes"
  /utilizations/{trainNum}:
    $ref: "utilizations.yaml#/paths/~1utilizations~1{trainNum}"
  /utilizations/{routeId}:
    $ref: "utilizations.yaml#/paths/~1utilizations~1{routeId}"
  /malfunctions:
    $ref: "malfunctions.yaml#/paths/~/malfunctions"
