openapi: 3.0.0
info:
  title: Bahn API
  description: Bahn API
  version: '1.0'

servers:
  - url: http://localhost/v1

paths:
  /routes:
    $ref: "passenger-info.v1.yaml#/paths/~1routes"
  /utilization/{trainNum}:
    $ref: "utilization.yml#/paths/~1utilization~1{trainNum}"
  /utilization/{routeId}:
    $ref: "utilization.yml#/paths/~1utilization~1{routeId}"
  /malfunctions:
    $ref: "malfunctions.yaml#/paths/~/malfunctions"
