openapi: 3.0.0
info:
  title: Utilization
  description: Utilization of trains on a given route
  version: '1.0'

paths:
  /utilization/{trainNum}:
    get:
      summary: Returns utilization for given train number
      tags:
       - 'Utilization'
      parameters:
        - name: trainNum
          in: path
          required: true
          description: Train number
          schema:
            type : string
      responses:
        '200':
          description: Utilization for given train
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/utilization'
                
        '404':
          description: Utilization not found

  /utilization/{routeId}:
    get:
      summary: Returns utilization for given route id
      tags:
       - 'Utilization'
      parameters:
        - name: routeId
          in: path
          required: true
          description: Route ID
          schema:
            type : integer
      responses:
        '200':
          description: Utilization for given route
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/utilization'
        '404':
          description: Utilization not found

components:
  schemas:
    utilization:
      type: object
      properties:
        train:
          type: string
          description: Train Number
          example: 'ICE372'
        utilization:
          type: integer
          description: Utilization
          example: 1
        
